### ISSUE TITLE
agent checkpoint in Scenario

### ISSUE THREAD

**Issue by KK666-AI** [IouJenLiu/PIC#2]
Dear Authors,

I am trying to reproduce the experiment results in your paper and select your method as one of the baselines in our paper.

In your code, I cannot find the agent checkpoint for the scenarios, such as simple_tag_n3. However, it seems that this checkpoint is necessary. How to handle this problem?

Best

**Comment by IouJenLiu** [comment]
Checkpoints are uploaded to multiagent-particle-envs/scripted_agent_ckpt/
Thanks!

**Comment by KK666-AI** [comment]
When I load the checkpoint, it has the following error:

`ModuleNotFoundError: No module named 'ddpg'`

The environment and python package versions are same with the ones as you said in readme.md.
