### ISSUE TITLE
only update the last agent's critic?

### ISSUE THREAD

**Issue by KK666-AI** [IouJenLiu/PIC#3]
Dear Author,

I notice that in your code, it seems that you only update the last agent's critic, is it correct?

More details:
In the line 200 at main_vec.py:
`value_losses.append(agent.update_critic_parameters(batch, i, args.shuffle))`
the i here refers to the last agent according to line 181.

In the function update_critic_parameters at ddpg_vec.py, agent_id is used to select this agent's reward.

Looking forward to here your feedback.
Best

**Comment by IouJenLiu** [comment]
Yes. In our setting, all agents share the same model and rewards.
