### ISSUE TITLE
The result about cooperative push 

### ISSUE THREAD

**Issue by Jarvis-K** [IouJenLiu/PIC#4]
I just ran the experiment without changing any hyper-parameters. The results of the cooperative-push-30 got a large variance for both `gcn_max` and `mlp`. Moreover, the `gcn_max` seems like got a similar result with `mlp`. 

This is much different like the spread experiment. Would u like to provide the hyper-parameters of coop-push to help me verify the influence of GCN?

**Comment by Jarvis-K** [comment]
The result is below:
<img width="411" alt="WeChatbbfe4468bec3e7b6b2bd98d79ca2c82e" src="https://user-images.githubusercontent.com/18642955/83096807-34a81700-a0d9-11ea-8b76-2a1f8ee98451.png">

The red curve and orange curve denote `gcn_max` and `mlp` respectively.

**Comment by IouJenLiu** [comment]
Please use the following hyper-parameters for coop-push
`--critic_updates_per_step 10 --updates_per_step 10 --num_steps 50`

**Comment by risufaj** [comment]
Hi @Jarvis-K 

Could you please share how you managed to get that particular plot?
