### ISSUE TITLE
No module named 'ddpg' when loading the scripted agents

### ISSUE THREAD

**Issue by qizhg** [IouJenLiu/PIC#5]
When creating simple_tag scenarios, I got the following error:

self.scripted_agents = torch.load(scripted_agent_ckpt)['agents']
  File "/Users/qizhg/miniconda3/envs/deeprl/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/qizhg/miniconda3/envs/deeprl/lib/python3.7/site-packages/torch/serialization.py", line 773, in _legacy_load
    result = unpickler.load()
ModuleNotFoundError: No module named 'ddpg'

**Comment by Isaac009** [comment]
I am having the same problem.
Any help, please.

**Comment by IouJenLiu** [comment]
Added the missing file. Please let me know if there is any issue. Thanks.

**Comment by qizhg** [comment]
> Added the missing file. Please let me know if there is any issue. Thanks.

Thank you!
