### ISSUE TITLE
episode rewards in simple_spread_n30 mismatch

### ISSUE THREAD

**Issue by Triple-ROCK** [IouJenLiu/PIC#7]
hello, I ran your code using `python main_vec.py --exp_name coop_navigation_n30 --scenario simple_spread_n30  --critic_type gcn_max  --cuda `, however, episode rewards start from -13000 instead of -28000 in the training curve you reported, could you tell me what may cause this problem?

**Comment by IouJenLiu** [comment]
Please use --num_steps 50
